// AUTO-GENERATED by fetch-images.js — per-lead home-page image paths + license PDF urls.
export const leadImages: Record<string, { images: Record<string, string>; imageLicenses: Record<string, string> }> = {
  "stat-logistics": {
    "images": {
      "hero": "/leads/stat-logistics/hero.jpg",
      "capabilities": "/leads/stat-logistics/capabilities.jpg",
      "operations": "/leads/stat-logistics/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/376969309?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/215273817?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/385346536?lang=en"
    }
  },
  "platinum-enterprises": {
    "images": {
      "hero": "/leads/platinum-enterprises/hero.jpg",
      "capabilities": "/leads/platinum-enterprises/capabilities.jpg",
      "operations": "/leads/platinum-enterprises/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/300833056?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/190917698?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/368140622?lang=en"
    }
  },
  "tcr-performance": {
    "images": {
      "hero": "/leads/tcr-performance/hero.jpg",
      "capabilities": "/leads/tcr-performance/capabilities.jpg",
      "operations": "/leads/tcr-performance/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/361671853?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/40945908?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/48528042?lang=en"
    }
  },
  "advanced-detection": {
    "images": {
      "hero": "/leads/advanced-detection/hero.jpg",
      "capabilities": "/leads/advanced-detection/capabilities.jpg",
      "operations": "/leads/advanced-detection/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/357665147?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/37489311?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31308144?lang=en"
    }
  },
  "haas-entertainment": {
    "images": {
      "hero": "/leads/haas-entertainment/hero.jpg",
      "capabilities": "/leads/haas-entertainment/capabilities.jpg",
      "operations": "/leads/haas-entertainment/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/279718820?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/362554739?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/38121430?lang=en"
    }
  },
  "laird-manufacturing": {
    "images": {
      "hero": "/leads/laird-manufacturing/hero.jpg",
      "capabilities": "/leads/laird-manufacturing/capabilities.jpg",
      "operations": "/leads/laird-manufacturing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/28861771?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/133621506?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/38699561?lang=en"
    }
  },
  "tmg": {
    "images": {
      "hero": "/leads/tmg/hero.jpg",
      "capabilities": "/leads/tmg/capabilities.jpg",
      "operations": "/leads/tmg/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/25618451?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/395553160?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/303105565?lang=en"
    }
  },
  "rl-engineering": {
    "images": {
      "hero": "/leads/rl-engineering/hero.jpg",
      "capabilities": "/leads/rl-engineering/capabilities.jpg",
      "operations": "/leads/rl-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/379831017?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/387909255?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/41435198?lang=en"
    }
  },
  "brenner-fiedler": {
    "images": {
      "hero": "/leads/brenner-fiedler/hero.jpg",
      "capabilities": "/leads/brenner-fiedler/capabilities.jpg",
      "operations": "/leads/brenner-fiedler/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/145795449?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/5242269?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/33692575?lang=en"
    }
  },
  "guntert-zimmerman": {
    "images": {
      "hero": "/leads/guntert-zimmerman/hero.jpg",
      "capabilities": "/leads/guntert-zimmerman/capabilities.jpg",
      "operations": "/leads/guntert-zimmerman/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/15585268?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/67194050?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/415341141?lang=en"
    }
  },
  "applied-motion": {
    "images": {
      "hero": "/leads/applied-motion/hero.jpg",
      "capabilities": "/leads/applied-motion/capabilities.jpg",
      "operations": "/leads/applied-motion/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/12275891?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/123486803?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/283233299?lang=en"
    }
  },
  "svt-associates": {
    "images": {
      "hero": "/leads/svt-associates/hero.jpg",
      "capabilities": "/leads/svt-associates/capabilities.jpg",
      "operations": "/leads/svt-associates/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/192375795?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/326581252?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31705374?lang=en"
    }
  }
};
