// AUTO-GENERATED by fetch-images.js — per-lead home-page image paths + license PDF urls.
export const leadImages: Record<string, { images: Record<string, string>; imageLicenses: Record<string, string> }> = {
  "stat-logistics": {
    "images": {
      "hero": "/leads/stat-logistics/hero.jpg",
      "capabilities": "/leads/stat-logistics/capabilities.jpg",
      "operations": "/leads/stat-logistics/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/376969309?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/215273817?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/385346536?lang=en"
    }
  },
  "platinum-enterprises": {
    "images": {
      "hero": "/leads/platinum-enterprises/hero.jpg",
      "capabilities": "/leads/platinum-enterprises/capabilities.jpg",
      "operations": "/leads/platinum-enterprises/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/300833056?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/190917698?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/368140622?lang=en"
    }
  },
  "tcr-performance": {
    "images": {
      "hero": "/leads/tcr-performance/hero.jpg",
      "capabilities": "/leads/tcr-performance/capabilities.jpg",
      "operations": "/leads/tcr-performance/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/361671853?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/40945908?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/48528042?lang=en"
    }
  },
  "advanced-detection": {
    "images": {
      "hero": "/leads/advanced-detection/hero.jpg",
      "capabilities": "/leads/advanced-detection/capabilities.jpg",
      "operations": "/leads/advanced-detection/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/357665147?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/37489311?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31308144?lang=en"
    }
  },
  "haas-entertainment": {
    "images": {
      "hero": "/leads/haas-entertainment/hero.jpg",
      "capabilities": "/leads/haas-entertainment/capabilities.jpg",
      "operations": "/leads/haas-entertainment/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/279718820?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/362554739?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/38121430?lang=en"
    }
  },
  "laird-manufacturing": {
    "images": {
      "hero": "/leads/laird-manufacturing/hero.jpg",
      "capabilities": "/leads/laird-manufacturing/capabilities.jpg",
      "operations": "/leads/laird-manufacturing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/28861771?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/133621506?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/38699561?lang=en"
    }
  },
  "tmg": {
    "images": {
      "hero": "/leads/tmg/hero.jpg",
      "capabilities": "/leads/tmg/capabilities.jpg",
      "operations": "/leads/tmg/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/25618451?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/395553160?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/303105565?lang=en"
    }
  },
  "rl-engineering": {
    "images": {
      "hero": "/leads/rl-engineering/hero.jpg",
      "capabilities": "/leads/rl-engineering/capabilities.jpg",
      "operations": "/leads/rl-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/379831017?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/387909255?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/41435198?lang=en"
    }
  },
  "brenner-fiedler": {
    "images": {
      "hero": "/leads/brenner-fiedler/hero.jpg",
      "capabilities": "/leads/brenner-fiedler/capabilities.jpg",
      "operations": "/leads/brenner-fiedler/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/145795449?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/5242269?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/33692575?lang=en"
    }
  },
  "guntert-zimmerman": {
    "images": {
      "hero": "/leads/guntert-zimmerman/hero.jpg",
      "capabilities": "/leads/guntert-zimmerman/capabilities.jpg",
      "operations": "/leads/guntert-zimmerman/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/15585268?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/67194050?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/415341141?lang=en"
    }
  },
  "applied-motion": {
    "images": {
      "hero": "/leads/applied-motion/hero.jpg",
      "capabilities": "/leads/applied-motion/capabilities.jpg",
      "operations": "/leads/applied-motion/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/12275891?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/123486803?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/283233299?lang=en"
    }
  },
  "svt-associates": {
    "images": {
      "hero": "/leads/svt-associates/hero.jpg",
      "capabilities": "/leads/svt-associates/capabilities.jpg",
      "operations": "/leads/svt-associates/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/192375795?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/326581252?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31705374?lang=en"
    }
  },
  "precision-mechanical": {
    "images": {
      "hero": "/leads/precision-mechanical/hero.jpg",
      "capabilities": "/leads/precision-mechanical/capabilities.jpg",
      "operations": "/leads/precision-mechanical/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/26735612?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/155970461?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/56623415?lang=en"
    }
  },
  "industrial-training": {
    "images": {
      "hero": "/leads/industrial-training/hero.jpg",
      "capabilities": "/leads/industrial-training/capabilities.jpg",
      "operations": "/leads/industrial-training/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/379941283?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/150093441?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/402813995?lang=en"
    }
  },
  "bell-electrical": {
    "images": {
      "hero": "/leads/bell-electrical/hero.jpg",
      "capabilities": "/leads/bell-electrical/capabilities.jpg",
      "operations": "/leads/bell-electrical/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/395732977?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/64138936?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/58516137?lang=en"
    }
  },
  "mc-sales": {
    "images": {
      "capabilities": "/leads/mc-sales/capabilities.jpg",
      "operations": "/leads/mc-sales/operations.jpg",
      "hero": "/leads/mc-sales/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/292178956?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/420042687?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/32882775?lang=en"
    }
  },
  "sonoma-valley": {
    "images": {
      "hero": "/leads/sonoma-valley/hero.jpg",
      "capabilities": "/leads/sonoma-valley/capabilities.jpg",
      "operations": "/leads/sonoma-valley/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/33945889?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/422262373?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/33996261?lang=en"
    }
  },
  "vacuum-sealers": {
    "images": {
      "hero": "/leads/vacuum-sealers/hero.jpg",
      "capabilities": "/leads/vacuum-sealers/capabilities.jpg",
      "operations": "/leads/vacuum-sealers/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/11429766?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/389787821?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/424862421?lang=en"
    }
  },
  "south-environmental": {
    "images": {
      "hero": "/leads/south-environmental/hero.jpg",
      "capabilities": "/leads/south-environmental/capabilities.jpg",
      "operations": "/leads/south-environmental/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/31964919?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/154447880?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/333379821?lang=en"
    }
  },
  "mhc-engineers": {
    "images": {
      "hero": "/leads/mhc-engineers/hero.jpg",
      "capabilities": "/leads/mhc-engineers/capabilities.jpg",
      "operations": "/leads/mhc-engineers/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/347114654?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/304644966?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/30896783?lang=en"
    }
  },
  "cj-machine": {
    "images": {
      "hero": "/leads/cj-machine/hero.jpg",
      "capabilities": "/leads/cj-machine/capabilities.jpg",
      "operations": "/leads/cj-machine/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/32958388?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/27230777?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/316851685?lang=en"
    }
  },
  "american-illumination": {
    "images": {
      "hero": "/leads/american-illumination/hero.jpg",
      "capabilities": "/leads/american-illumination/capabilities.jpg",
      "operations": "/leads/american-illumination/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/398201697?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/424589616?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/150092669?lang=en"
    }
  },
  "r-g": {
    "images": {
      "hero": "/leads/r-g/hero.jpg",
      "capabilities": "/leads/r-g/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/23035089?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/143592122?lang=en"
    }
  },
  "suppose-u": {
    "images": {
      "hero": "/leads/suppose-u/hero.jpg",
      "capabilities": "/leads/suppose-u/capabilities.jpg",
      "operations": "/leads/suppose-u/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/250319663?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/234389385?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/419685576?lang=en"
    }
  },
  "creative-air": {
    "images": {
      "hero": "/leads/creative-air/hero.jpg",
      "capabilities": "/leads/creative-air/capabilities.jpg",
      "operations": "/leads/creative-air/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/36027011?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/62249472?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/426294443?lang=en"
    }
  },
  "norcal-battery": {
    "images": {
      "hero": "/leads/norcal-battery/hero.jpg",
      "operations": "/leads/norcal-battery/operations.jpg",
      "capabilities": "/leads/norcal-battery/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/378951703?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/420225298?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/332085337?lang=en"
    }
  },
  "roy-e": {
    "images": {
      "hero": "/leads/roy-e/hero.jpg",
      "capabilities": "/leads/roy-e/capabilities.jpg",
      "operations": "/leads/roy-e/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/345138068?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/411596809?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/132294684?lang=en"
    }
  },
  "kermetico-hvaf": {
    "images": {
      "hero": "/leads/kermetico-hvaf/hero.jpg",
      "capabilities": "/leads/kermetico-hvaf/capabilities.jpg",
      "operations": "/leads/kermetico-hvaf/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/312483763?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/125379846?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/312483763?lang=en"
    }
  },
  "imperial-ambulance": {
    "images": {
      "hero": "/leads/imperial-ambulance/hero.jpg",
      "capabilities": "/leads/imperial-ambulance/capabilities.jpg",
      "operations": "/leads/imperial-ambulance/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/48917484?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/9161846?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/265614195?lang=en"
    }
  },
  "protech-thermal": {
    "images": {
      "operations": "/leads/protech-thermal/operations.jpg"
    },
    "imageLicenses": {
      "operations": "https://www.magnific.com/profile/license/pdf/423395358?lang=en"
    }
  },
  "denise-duffy": {
    "images": {
      "capabilities": "/leads/denise-duffy/capabilities.jpg",
      "operations": "/leads/denise-duffy/operations.jpg",
      "hero": "/leads/denise-duffy/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/374457809?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/212516210?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/372420890?lang=en"
    }
  },
  "aopec-automotive": {
    "images": {
      "capabilities": "/leads/aopec-automotive/capabilities.jpg",
      "hero": "/leads/aopec-automotive/hero.jpg",
      "operations": "/leads/aopec-automotive/operations.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/39353968?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/341077535?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/382476706?lang=en"
    }
  },
  "acculoader": {
    "images": {
      "hero": "/leads/acculoader/hero.jpg",
      "operations": "/leads/acculoader/operations.jpg",
      "capabilities": "/leads/acculoader/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/39043846?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/95518273?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/352183435?lang=en"
    }
  },
  "custom-machining": {
    "images": {
      "capabilities": "/leads/custom-machining/capabilities.jpg",
      "operations": "/leads/custom-machining/operations.jpg",
      "hero": "/leads/custom-machining/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/26735612?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/324145235?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/21812626?lang=en"
    }
  },
  "myotek": {
    "images": {
      "hero": "/leads/myotek/hero.jpg",
      "capabilities": "/leads/myotek/capabilities.jpg",
      "operations": "/leads/myotek/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/416512710?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/283623146?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/244451184?lang=en"
    }
  },
  "design-heating": {
    "images": {
      "hero": "/leads/design-heating/hero.jpg",
      "capabilities": "/leads/design-heating/capabilities.jpg",
      "operations": "/leads/design-heating/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/36921762?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/358123966?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/166660169?lang=en"
    }
  },
  "am-sun": {
    "images": {
      "hero": "/leads/am-sun/hero.jpg",
      "capabilities": "/leads/am-sun/capabilities.jpg",
      "operations": "/leads/am-sun/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/134244964?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/425267786?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/287776697?lang=en"
    }
  },
  "universal-automation": {
    "images": {
      "hero": "/leads/universal-automation/hero.jpg",
      "capabilities": "/leads/universal-automation/capabilities.jpg",
      "operations": "/leads/universal-automation/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/411596805?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/390481059?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31621885?lang=en"
    }
  },
  "fresh-quality": {
    "images": {
      "hero": "/leads/fresh-quality/hero.jpg",
      "capabilities": "/leads/fresh-quality/capabilities.jpg",
      "operations": "/leads/fresh-quality/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/337810439?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/267927556?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/416292847?lang=en"
    }
  },
  "tcw-equipment": {
    "images": {
      "hero": "/leads/tcw-equipment/hero.jpg",
      "capabilities": "/leads/tcw-equipment/capabilities.jpg",
      "operations": "/leads/tcw-equipment/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/157696828?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/6634777?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/283808530?lang=en"
    }
  },
  "heavy-motions": {
    "images": {
      "hero": "/leads/heavy-motions/hero.jpg",
      "capabilities": "/leads/heavy-motions/capabilities.jpg",
      "operations": "/leads/heavy-motions/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/51629316?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/416182269?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/424231257?lang=en"
    }
  },
  "greentek": {
    "images": {
      "hero": "/leads/greentek/hero.jpg",
      "capabilities": "/leads/greentek/capabilities.jpg",
      "operations": "/leads/greentek/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/27104701?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/268308711?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/14519323?lang=en"
    }
  },
  "csa-srl": {
    "images": {
      "hero": "/leads/csa-srl/hero.jpg",
      "capabilities": "/leads/csa-srl/capabilities.jpg",
      "operations": "/leads/csa-srl/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/294955456?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/35664509?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/332160678?lang=en"
    }
  },
  "e-s": {
    "images": {
      "hero": "/leads/e-s/hero.jpg",
      "capabilities": "/leads/e-s/capabilities.jpg",
      "operations": "/leads/e-s/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/285230381?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/37224717?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/10666387?lang=en"
    }
  },
  "central-media": {
    "images": {
      "hero": "/leads/central-media/hero.jpg",
      "capabilities": "/leads/central-media/capabilities.jpg",
      "operations": "/leads/central-media/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/392544254?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/329817447?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/409071223?lang=en"
    }
  },
  "4m-engineering": {
    "images": {
      "hero": "/leads/4m-engineering/hero.jpg",
      "capabilities": "/leads/4m-engineering/capabilities.jpg",
      "operations": "/leads/4m-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/29183068?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/81384099?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/170932323?lang=en"
    }
  },
  "a-tech-consulting": {
    "images": {
      "hero": "/leads/a-tech-consulting/hero.jpg",
      "capabilities": "/leads/a-tech-consulting/capabilities.jpg",
      "operations": "/leads/a-tech-consulting/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/306577262?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/250131233?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/310868989?lang=en"
    }
  },
  "ability-tri-modal": {
    "images": {
      "hero": "/leads/ability-tri-modal/hero.jpg",
      "capabilities": "/leads/ability-tri-modal/capabilities.jpg",
      "operations": "/leads/ability-tri-modal/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/367073002?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/36263458?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/362298050?lang=en"
    }
  },
  "acw-steel": {
    "images": {
      "hero": "/leads/acw-steel/hero.jpg",
      "capabilities": "/leads/acw-steel/capabilities.jpg",
      "operations": "/leads/acw-steel/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/422478648?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/126005027?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/106907037?lang=en"
    }
  },
  "american-performance": {
    "images": {
      "capabilities": "/leads/american-performance/capabilities.jpg",
      "operations": "/leads/american-performance/operations.jpg",
      "hero": "/leads/american-performance/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/359953793?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/193690754?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/144141867?lang=en"
    }
  },
  "american-rubber": {
    "images": {
      "capabilities": "/leads/american-rubber/capabilities.jpg",
      "operations": "/leads/american-rubber/operations.jpg",
      "hero": "/leads/american-rubber/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/4159900?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/376314937?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/380994694?lang=en"
    }
  },
  "appleton-electronics": {
    "images": {
      "hero": "/leads/appleton-electronics/hero.jpg",
      "capabilities": "/leads/appleton-electronics/capabilities.jpg",
      "operations": "/leads/appleton-electronics/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/330084855?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/349526819?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/149604495?lang=en"
    }
  },
  "apt-electronics": {
    "images": {
      "hero": "/leads/apt-electronics/hero.jpg",
      "capabilities": "/leads/apt-electronics/capabilities.jpg",
      "operations": "/leads/apt-electronics/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/362205782?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/362868288?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/67267861?lang=en"
    }
  },
  "atlas-environmental": {
    "images": {
      "capabilities": "/leads/atlas-environmental/capabilities.jpg",
      "hero": "/leads/atlas-environmental/hero.jpg",
      "operations": "/leads/atlas-environmental/operations.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/242300968?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/388899493?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/226041568?lang=en"
    }
  },
  "bl-paletten": {
    "images": {
      "hero": "/leads/bl-paletten/hero.jpg",
      "capabilities": "/leads/bl-paletten/capabilities.jpg",
      "operations": "/leads/bl-paletten/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/420652582?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/420652507?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/417217241?lang=en"
    }
  },
  "brg-racing": {
    "images": {
      "hero": "/leads/brg-racing/hero.jpg",
      "capabilities": "/leads/brg-racing/capabilities.jpg",
      "operations": "/leads/brg-racing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/424725833?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/173699562?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/426074037?lang=en"
    }
  },
  "cal-west": {
    "images": {
      "hero": "/leads/cal-west/hero.jpg",
      "capabilities": "/leads/cal-west/capabilities.jpg",
      "operations": "/leads/cal-west/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/147160582?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/136317163?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/292804347?lang=en"
    }
  },
  "central-irrigation": {
    "images": {
      "hero": "/leads/central-irrigation/hero.jpg",
      "capabilities": "/leads/central-irrigation/capabilities.jpg",
      "operations": "/leads/central-irrigation/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/94112425?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/18675750?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/16095083?lang=en"
    }
  },
  "custom-engineering": {
    "images": {
      "hero": "/leads/custom-engineering/hero.jpg",
      "capabilities": "/leads/custom-engineering/capabilities.jpg",
      "operations": "/leads/custom-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/361671853?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/408855494?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/424786105?lang=en"
    }
  },
  "designit-prototype": {
    "images": {
      "hero": "/leads/designit-prototype/hero.jpg",
      "capabilities": "/leads/designit-prototype/capabilities.jpg",
      "operations": "/leads/designit-prototype/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/333889408?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/361351176?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/144473056?lang=en"
    }
  },
  "direct-appliance": {
    "images": {
      "hero": "/leads/direct-appliance/hero.jpg",
      "capabilities": "/leads/direct-appliance/capabilities.jpg",
      "operations": "/leads/direct-appliance/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/343421052?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/22363119?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/407163851?lang=en"
    }
  },
  "diversified-waterscapes": {
    "images": {
      "hero": "/leads/diversified-waterscapes/hero.jpg",
      "operations": "/leads/diversified-waterscapes/operations.jpg",
      "capabilities": "/leads/diversified-waterscapes/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/281169796?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/17354575?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/120623335?lang=en"
    }
  },
  "empire-marketing": {
    "images": {
      "hero": "/leads/empire-marketing/hero.jpg",
      "capabilities": "/leads/empire-marketing/capabilities.jpg",
      "operations": "/leads/empire-marketing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/347222317?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/39353972?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/61339280?lang=en"
    }
  },
  "engineered-products": {
    "images": {
      "hero": "/leads/engineered-products/hero.jpg",
      "capabilities": "/leads/engineered-products/capabilities.jpg",
      "operations": "/leads/engineered-products/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/424231257?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/427476182?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/25856003?lang=en"
    }
  },
  "gilmar-engineering": {
    "images": {
      "hero": "/leads/gilmar-engineering/hero.jpg",
      "capabilities": "/leads/gilmar-engineering/capabilities.jpg",
      "operations": "/leads/gilmar-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/406929595?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/384461258?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/22801611?lang=en"
    }
  },
  "golden-state": {
    "images": {
      "hero": "/leads/golden-state/hero.jpg",
      "operations": "/leads/golden-state/operations.jpg",
      "capabilities": "/leads/golden-state/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/238939647?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/339748371?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/416536069?lang=en"
    }
  },
  "gp-landscape": {
    "images": {
      "capabilities": "/leads/gp-landscape/capabilities.jpg",
      "operations": "/leads/gp-landscape/operations.jpg",
      "hero": "/leads/gp-landscape/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/394475328?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/411719568?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/182639080?lang=en"
    }
  },
  "green-mary": {
    "images": {
      "hero": "/leads/green-mary/hero.jpg",
      "capabilities": "/leads/green-mary/capabilities.jpg",
      "operations": "/leads/green-mary/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/283063635?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/40085419?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/278764228?lang=en"
    }
  },
  "heleon-safety": {
    "images": {
      "hero": "/leads/heleon-safety/hero.jpg",
      "capabilities": "/leads/heleon-safety/capabilities.jpg",
      "operations": "/leads/heleon-safety/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/426462338?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/427913173?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/20336126?lang=en"
    }
  },
  "hydraulic-power": {
    "images": {
      "hero": "/leads/hydraulic-power/hero.jpg",
      "capabilities": "/leads/hydraulic-power/capabilities.jpg",
      "operations": "/leads/hydraulic-power/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/117612706?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/17935999?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/383315997?lang=en"
    }
  },
  "integrated-motion": {
    "images": {
      "hero": "/leads/integrated-motion/hero.jpg",
      "capabilities": "/leads/integrated-motion/capabilities.jpg",
      "operations": "/leads/integrated-motion/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/132159341?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/329847564?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/51393502?lang=en"
    }
  },
  "interior-specialties": {
    "images": {
      "hero": "/leads/interior-specialties/hero.jpg",
      "capabilities": "/leads/interior-specialties/capabilities.jpg",
      "operations": "/leads/interior-specialties/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/191286944?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/300226439?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/129790218?lang=en"
    }
  },
  "jasper-electronics": {
    "images": {
      "operations": "/leads/jasper-electronics/operations.jpg",
      "hero": "/leads/jasper-electronics/hero.jpg",
      "capabilities": "/leads/jasper-electronics/capabilities.jpg"
    },
    "imageLicenses": {
      "operations": "https://www.magnific.com/profile/license/pdf/417003019?lang=en",
      "hero": "https://www.magnific.com/profile/license/pdf/190781178?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/257418464?lang=en"
    }
  },
  "jmg-solutions": {
    "images": {
      "hero": "/leads/jmg-solutions/hero.jpg",
      "capabilities": "/leads/jmg-solutions/capabilities.jpg",
      "operations": "/leads/jmg-solutions/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/379541754?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/268154190?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/245681986?lang=en"
    }
  },
  "johnson-manufacturing": {
    "images": {
      "hero": "/leads/johnson-manufacturing/hero.jpg",
      "capabilities": "/leads/johnson-manufacturing/capabilities.jpg",
      "operations": "/leads/johnson-manufacturing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/138751542?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/381785773?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/414567612?lang=en"
    }
  },
  "km-associates": {
    "images": {
      "hero": "/leads/km-associates/hero.jpg",
      "capabilities": "/leads/km-associates/capabilities.jpg",
      "operations": "/leads/km-associates/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/320863596?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/378444694?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/173345116?lang=en"
    }
  },
  "l9-electric": {
    "images": {
      "hero": "/leads/l9-electric/hero.jpg",
      "operations": "/leads/l9-electric/operations.jpg",
      "capabilities": "/leads/l9-electric/capabilities.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/391672545?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/409670153?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/369050997?lang=en"
    }
  },
  "lb-laboratories": {
    "images": {
      "hero": "/leads/lb-laboratories/hero.jpg",
      "capabilities": "/leads/lb-laboratories/capabilities.jpg",
      "operations": "/leads/lb-laboratories/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/167902030?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/406929595?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/288506072?lang=en"
    }
  },
  "jkindustries": {
    "images": {
      "hero": "/leads/jkindustries/hero.jpg",
      "capabilities": "/leads/jkindustries/capabilities.jpg",
      "operations": "/leads/jkindustries/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/26150534?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/387229497?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/376256791?lang=en"
    }
  },
  "kamal-trading": {
    "images": {
      "hero": "/leads/kamal-trading/hero.jpg",
      "capabilities": "/leads/kamal-trading/capabilities.jpg",
      "operations": "/leads/kamal-trading/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/28711601?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/18922519?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/328573042?lang=en"
    }
  },
  "kasai-consulting": {
    "images": {
      "capabilities": "/leads/kasai-consulting/capabilities.jpg",
      "operations": "/leads/kasai-consulting/operations.jpg",
      "hero": "/leads/kasai-consulting/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/356243876?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/360638235?lang=en"
    }
  },
  "keco": {
    "images": {
      "hero": "/leads/keco/hero.jpg",
      "capabilities": "/leads/keco/capabilities.jpg",
      "operations": "/leads/keco/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/418646180?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/418646180?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/224203104?lang=en"
    }
  },
  "la-valves": {
    "images": {
      "hero": "/leads/la-valves/hero.jpg",
      "capabilities": "/leads/la-valves/capabilities.jpg",
      "operations": "/leads/la-valves/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/248284364?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/391430762?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/425300075?lang=en"
    }
  },
  "lexmar-distribution": {
    "images": {
      "hero": "/leads/lexmar-distribution/hero.jpg",
      "capabilities": "/leads/lexmar-distribution/capabilities.jpg",
      "operations": "/leads/lexmar-distribution/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/320959395?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/91287884?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/32499833?lang=en"
    }
  },
  "linear-design": {
    "images": {
      "hero": "/leads/linear-design/hero.jpg",
      "capabilities": "/leads/linear-design/capabilities.jpg",
      "operations": "/leads/linear-design/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/273678800?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/383803270?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/223019034?lang=en"
    }
  },
  "lodi-iron": {
    "images": {
      "capabilities": "/leads/lodi-iron/capabilities.jpg",
      "operations": "/leads/lodi-iron/operations.jpg",
      "hero": "/leads/lodi-iron/hero.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/143591305?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/415670745?lang=en"
    }
  },
  "m-m": {
    "images": {
      "hero": "/leads/m-m/hero.jpg",
      "capabilities": "/leads/m-m/capabilities.jpg",
      "operations": "/leads/m-m/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/398860358?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/397148700?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/25423612?lang=en"
    }
  },
  "macfab-welding": {
    "images": {
      "hero": "/leads/macfab-welding/hero.jpg",
      "capabilities": "/leads/macfab-welding/capabilities.jpg",
      "operations": "/leads/macfab-welding/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/19653353?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/378147498?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/47918638?lang=en"
    }
  },
  "machinery-resources": {
    "images": {
      "hero": "/leads/machinery-resources/hero.jpg",
      "capabilities": "/leads/machinery-resources/capabilities.jpg",
      "operations": "/leads/machinery-resources/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/32958388?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/26128669?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/403839835?lang=en"
    }
  },
  "marmol-export": {
    "images": {
      "hero": "/leads/marmol-export/hero.jpg",
      "capabilities": "/leads/marmol-export/capabilities.jpg",
      "operations": "/leads/marmol-export/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/421080327?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/354800141?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/410346062?lang=en"
    }
  },
  "material-flow": {
    "images": {
      "hero": "/leads/material-flow/hero.jpg",
      "capabilities": "/leads/material-flow/capabilities.jpg",
      "operations": "/leads/material-flow/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/37320135?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/400593928?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/400593928?lang=en"
    }
  },
  "menches-tool": {
    "images": {
      "hero": "/leads/menches-tool/hero.jpg",
      "capabilities": "/leads/menches-tool/capabilities.jpg",
      "operations": "/leads/menches-tool/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/144142005?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/45737391?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/395553160?lang=en"
    }
  },
  "mill-mike": {
    "images": {
      "hero": "/leads/mill-mike/hero.jpg",
      "capabilities": "/leads/mill-mike/capabilities.jpg",
      "operations": "/leads/mill-mike/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/144141867?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/348800598?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/363783362?lang=en"
    }
  },
  "mooney-industrials": {
    "images": {
      "hero": "/leads/mooney-industrials/hero.jpg",
      "capabilities": "/leads/mooney-industrials/capabilities.jpg",
      "operations": "/leads/mooney-industrials/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/342864040?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/342864040?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/224734233?lang=en"
    }
  },
  "motor-city": {
    "images": {
      "hero": "/leads/motor-city/hero.jpg",
      "capabilities": "/leads/motor-city/capabilities.jpg",
      "operations": "/leads/motor-city/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/22495568?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/166545576?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/166545576?lang=en"
    }
  },
  "nelson-air": {
    "images": {
      "hero": "/leads/nelson-air/hero.jpg",
      "capabilities": "/leads/nelson-air/capabilities.jpg",
      "operations": "/leads/nelson-air/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/398816477?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/238519075?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/32177252?lang=en"
    }
  },
  "nelson-auctions": {
    "images": {
      "hero": "/leads/nelson-auctions/hero.jpg",
      "capabilities": "/leads/nelson-auctions/capabilities.jpg",
      "operations": "/leads/nelson-auctions/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/28451485?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/321222478?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/337911268?lang=en"
    }
  },
  "network-delivery": {
    "images": {
      "hero": "/leads/network-delivery/hero.jpg",
      "capabilities": "/leads/network-delivery/capabilities.jpg",
      "operations": "/leads/network-delivery/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/387341515?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/380300597?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/372853663?lang=en"
    }
  },
  "neuro-logic": {
    "images": {
      "hero": "/leads/neuro-logic/hero.jpg",
      "capabilities": "/leads/neuro-logic/capabilities.jpg",
      "operations": "/leads/neuro-logic/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/381607846?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/352408442?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/352408442?lang=en"
    }
  },
  "nielsen-technologies": {
    "images": {
      "hero": "/leads/nielsen-technologies/hero.jpg",
      "capabilities": "/leads/nielsen-technologies/capabilities.jpg",
      "operations": "/leads/nielsen-technologies/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/415456176?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/283810741?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/404928718?lang=en"
    }
  },
  "north-texas": {
    "images": {
      "hero": "/leads/north-texas/hero.jpg",
      "capabilities": "/leads/north-texas/capabilities.jpg",
      "operations": "/leads/north-texas/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/138831560?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/76792115?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/388082431?lang=en"
    }
  },
  "pacific-kiln": {
    "images": {
      "hero": "/leads/pacific-kiln/hero.jpg",
      "capabilities": "/leads/pacific-kiln/capabilities.jpg",
      "operations": "/leads/pacific-kiln/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/22832037?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/155183645?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/347851232?lang=en"
    }
  },
  "pade": {
    "images": {
      "hero": "/leads/pade/hero.jpg",
      "capabilities": "/leads/pade/capabilities.jpg",
      "operations": "/leads/pade/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/65535199?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/373955172?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/331039990?lang=en"
    }
  },
  "pegasus-bicycle": {
    "images": {
      "hero": "/leads/pegasus-bicycle/hero.jpg",
      "capabilities": "/leads/pegasus-bicycle/capabilities.jpg",
      "operations": "/leads/pegasus-bicycle/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/318443664?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/420083845?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/346170860?lang=en"
    }
  },
  "pirtek-power": {
    "images": {
      "hero": "/leads/pirtek-power/hero.jpg",
      "capabilities": "/leads/pirtek-power/capabilities.jpg",
      "operations": "/leads/pirtek-power/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/183242897?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/183242897?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/413227227?lang=en"
    }
  },
  "pirtek-san": {
    "images": {
      "hero": "/leads/pirtek-san/hero.jpg",
      "capabilities": "/leads/pirtek-san/capabilities.jpg",
      "operations": "/leads/pirtek-san/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/175222523?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/328241709?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/51505394?lang=en"
    }
  },
  "polar-power": {
    "images": {
      "capabilities": "/leads/polar-power/capabilities.jpg",
      "operations": "/leads/polar-power/operations.jpg"
    },
    "imageLicenses": {
      "capabilities": "https://www.magnific.com/profile/license/pdf/283097620?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/72547283?lang=en"
    }
  },
  "potter-gmh-technologies": {
    "images": {
      "hero": "/leads/potter-gmh-technologies/hero.jpg",
      "capabilities": "/leads/potter-gmh-technologies/capabilities.jpg",
      "operations": "/leads/potter-gmh-technologies/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/342339216?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/427898655?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/378927990?lang=en"
    }
  },
  "power-transmission": {
    "images": {
      "hero": "/leads/power-transmission/hero.jpg",
      "capabilities": "/leads/power-transmission/capabilities.jpg",
      "operations": "/leads/power-transmission/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/137740178?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/2998540?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/422775167?lang=en"
    }
  },
  "prime-machine": {
    "images": {
      "hero": "/leads/prime-machine/hero.jpg",
      "capabilities": "/leads/prime-machine/capabilities.jpg",
      "operations": "/leads/prime-machine/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/21926876?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/348802061?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/326040193?lang=en"
    }
  },
  "proper-quality": {
    "images": {
      "hero": "/leads/proper-quality/hero.jpg",
      "capabilities": "/leads/proper-quality/capabilities.jpg",
      "operations": "/leads/proper-quality/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/420723229?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/426361494?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/420607811?lang=en"
    }
  },
  "protek-cnc": {
    "images": {
      "hero": "/leads/protek-cnc/hero.jpg",
      "capabilities": "/leads/protek-cnc/capabilities.jpg",
      "operations": "/leads/protek-cnc/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/143591103?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/427616516?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/359636116?lang=en"
    }
  },
  "provoast-automation": {
    "images": {
      "hero": "/leads/provoast-automation/hero.jpg",
      "capabilities": "/leads/provoast-automation/capabilities.jpg",
      "operations": "/leads/provoast-automation/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/278973240?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/144472944?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/355918197?lang=en"
    }
  },
  "industrial-solution": {
    "images": {
      "hero": "/leads/industrial-solution/hero.jpg",
      "capabilities": "/leads/industrial-solution/capabilities.jpg",
      "operations": "/leads/industrial-solution/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/24394971?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/347375991?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/403389273?lang=en"
    }
  },
  "abm-scale": {
    "images": {
      "hero": "/leads/abm-scale/hero.jpg",
      "capabilities": "/leads/abm-scale/capabilities.jpg",
      "operations": "/leads/abm-scale/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/267215179?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/369306838?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/267215179?lang=en"
    }
  },
  "advanced-laser": {
    "images": {
      "hero": "/leads/advanced-laser/hero.jpg",
      "capabilities": "/leads/advanced-laser/capabilities.jpg",
      "operations": "/leads/advanced-laser/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/143591309?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/409334216?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/80797043?lang=en"
    }
  },
  "baca-marine": {
    "images": {
      "hero": "/leads/baca-marine/hero.jpg",
      "capabilities": "/leads/baca-marine/capabilities.jpg",
      "operations": "/leads/baca-marine/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/425330335?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/369307406?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/49350056?lang=en"
    }
  },
  "bay-machine": {
    "images": {
      "hero": "/leads/bay-machine/hero.jpg",
      "capabilities": "/leads/bay-machine/capabilities.jpg",
      "operations": "/leads/bay-machine/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/411691679?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/284724891?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/158957429?lang=en"
    }
  },
  "bertschi-instrumentos": {
    "images": {
      "hero": "/leads/bertschi-instrumentos/hero.jpg",
      "capabilities": "/leads/bertschi-instrumentos/capabilities.jpg",
      "operations": "/leads/bertschi-instrumentos/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/335933373?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/263517781?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/417275316?lang=en"
    }
  },
  "bianchi-quadri": {
    "images": {
      "hero": "/leads/bianchi-quadri/hero.jpg",
      "capabilities": "/leads/bianchi-quadri/capabilities.jpg",
      "operations": "/leads/bianchi-quadri/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/290595923?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/184831948?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/332185727?lang=en"
    }
  },
  "carlton-engineering": {
    "images": {
      "hero": "/leads/carlton-engineering/hero.jpg",
      "capabilities": "/leads/carlton-engineering/capabilities.jpg",
      "operations": "/leads/carlton-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/412109899?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/297092003?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/315169632?lang=en"
    }
  },
  "central-refrigeration": {
    "images": {
      "hero": "/leads/central-refrigeration/hero.jpg",
      "capabilities": "/leads/central-refrigeration/capabilities.jpg",
      "operations": "/leads/central-refrigeration/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/36921686?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/369309312?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/262889965?lang=en"
    }
  },
  "conesys": {
    "images": {
      "hero": "/leads/conesys/hero.jpg",
      "capabilities": "/leads/conesys/capabilities.jpg",
      "operations": "/leads/conesys/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/106369092?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/422819218?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/401345062?lang=en"
    }
  },
  "confluence-environmental": {
    "images": {
      "hero": "/leads/confluence-environmental/hero.jpg",
      "capabilities": "/leads/confluence-environmental/capabilities.jpg",
      "operations": "/leads/confluence-environmental/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/160575945?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/143806253?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/198224614?lang=en"
    }
  },
  "cornerstone-services": {
    "images": {
      "hero": "/leads/cornerstone-services/hero.jpg",
      "capabilities": "/leads/cornerstone-services/capabilities.jpg",
      "operations": "/leads/cornerstone-services/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/80383515?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/426144122?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/31662173?lang=en"
    }
  },
  "d-h": {
    "images": {
      "hero": "/leads/d-h/hero.jpg",
      "capabilities": "/leads/d-h/capabilities.jpg",
      "operations": "/leads/d-h/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/32453713?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/46281367?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/350130145?lang=en"
    }
  },
  "deep-root": {
    "images": {
      "hero": "/leads/deep-root/hero.jpg",
      "capabilities": "/leads/deep-root/capabilities.jpg",
      "operations": "/leads/deep-root/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/399531019?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/12131175?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/72673321?lang=en"
    }
  },
  "elite-industrial": {
    "images": {
      "hero": "/leads/elite-industrial/hero.jpg",
      "capabilities": "/leads/elite-industrial/capabilities.jpg",
      "operations": "/leads/elite-industrial/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/200686712?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/356319372?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/124645731?lang=en"
    }
  },
  "euroclydon-engineering": {
    "images": {
      "hero": "/leads/euroclydon-engineering/hero.jpg",
      "capabilities": "/leads/euroclydon-engineering/capabilities.jpg",
      "operations": "/leads/euroclydon-engineering/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/366601737?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/416966649?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/291070082?lang=en"
    }
  },
  "fork-lift": {
    "images": {
      "hero": "/leads/fork-lift/hero.jpg",
      "capabilities": "/leads/fork-lift/capabilities.jpg",
      "operations": "/leads/fork-lift/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/380222122?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/188056141?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/221604489?lang=en"
    }
  },
  "ga-systems": {
    "images": {
      "hero": "/leads/ga-systems/hero.jpg",
      "capabilities": "/leads/ga-systems/capabilities.jpg",
      "operations": "/leads/ga-systems/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/369753128?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/369753128?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/244685986?lang=en"
    }
  },
  "gifts-of": {
    "images": {
      "hero": "/leads/gifts-of/hero.jpg",
      "capabilities": "/leads/gifts-of/capabilities.jpg",
      "operations": "/leads/gifts-of/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/81205186?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/390220268?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/390220268?lang=en"
    }
  },
  "global-construction": {
    "images": {
      "hero": "/leads/global-construction/hero.jpg",
      "capabilities": "/leads/global-construction/capabilities.jpg",
      "operations": "/leads/global-construction/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/134273328?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/183368470?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/394415647?lang=en"
    }
  },
  "great-way": {
    "images": {
      "hero": "/leads/great-way/hero.jpg",
      "capabilities": "/leads/great-way/capabilities.jpg",
      "operations": "/leads/great-way/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/275646566?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/338782617?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/363247498?lang=en"
    }
  },
  "heinzen-manufacturing": {
    "images": {
      "hero": "/leads/heinzen-manufacturing/hero.jpg",
      "capabilities": "/leads/heinzen-manufacturing/capabilities.jpg",
      "operations": "/leads/heinzen-manufacturing/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/353474857?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/158849735?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/245459071?lang=en"
    }
  },
  "innosense": {
    "images": {
      "hero": "/leads/innosense/hero.jpg",
      "capabilities": "/leads/innosense/capabilities.jpg",
      "operations": "/leads/innosense/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/332626316?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/336230940?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/3482080?lang=en"
    }
  },
  "inverse-solutions": {
    "images": {
      "hero": "/leads/inverse-solutions/hero.jpg",
      "capabilities": "/leads/inverse-solutions/capabilities.jpg",
      "operations": "/leads/inverse-solutions/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/143591103?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/335993342?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/6079550?lang=en"
    }
  },
  "jaccard": {
    "images": {
      "hero": "/leads/jaccard/hero.jpg",
      "capabilities": "/leads/jaccard/capabilities.jpg",
      "operations": "/leads/jaccard/operations.jpg"
    },
    "imageLicenses": {
      "hero": "https://www.magnific.com/profile/license/pdf/143483914?lang=en",
      "capabilities": "https://www.magnific.com/profile/license/pdf/13232447?lang=en",
      "operations": "https://www.magnific.com/profile/license/pdf/245459071?lang=en"
    }
  }
};
